# Generated by Django 3.2.20 on 2023-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=5, unique=True)),
                ('owner', models.CharField(max_length=75, unique=True)),
                ('pausible', models.BooleanField(default=False)),
                ('skippable', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
