# Generated by Django 3.2.13 on 2023-09-24 13:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_skippable_group_wants_to_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='identifier',
            field=models.CharField(default=api.models.create_random_identifier, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
